services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    
  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
